/** Render a Report as Markdown (for PR comments / CI artifacts). */

import { CATEGORY_LABELS, type Report } from "../types.js";

const ICON = { error: "✗", warning: "⚠", info: "ℹ", pass: "✓" } as const;

function claimsTable(obj: Record<string, unknown>): string[] {
  const rows = Object.entries(obj).map(
    ([k, v]) => `| \`${k}\` | ${String(JSON.stringify(v)).replace(/\|/g, "\\|").slice(0, 80)} |`,
  );
  return rows.length ? [`| Claim | Value |`, `| ----- | ----- |`, ...rows] : ["_(empty)_"];
}

export function toMarkdown(report: Report): string {
  const s = report.summary;
  const out: string[] = [];
  out.push(`# jwtlens report`);
  out.push("");
  out.push(`**${s.score}/100 (${s.grade})** — ${s.errors} error(s), ${s.warnings} warning(s), ${s.infos} info(s)`);
  out.push("");

  if (report.verification) {
    const v = report.verification;
    out.push(`**Signature:** ${v.valid ? "✓ verified" : "✗ not verified"} (${v.alg}) — ${v.reason}`);
    out.push("");
  }

  out.push(`## Header`);
  out.push(...claimsTable(report.header));
  out.push("");
  out.push(`## Payload`);
  out.push(...claimsTable(report.payload));
  out.push("");

  out.push(`## Findings`);
  out.push("");
  if (report.findings.length === 0) {
    out.push(`✓ No issues found.`);
  } else {
    out.push(`| | Category | Rule | Issue | Fix |`);
    out.push(`| - | -------- | ---- | ----- | --- |`);
    for (const f of report.findings) {
      const fix = (f.fix ?? "").split("\n")[0]!.replace(/\|/g, "\\|");
      out.push(`| ${ICON[f.severity]} | ${CATEGORY_LABELS[f.category]} | \`${f.rule}\` | ${f.title.replace(/\|/g, "\\|")} | ${fix} |`);
    }
  }
  out.push("");
  out.push(`---`);
  out.push(`<sub>Generated by jwtlens v${report.version} · ${report.generatedAt} · nothing left your machine.</sub>`);
  out.push("");
  return out.join("\n");
}
